#!/usr/bin/env python3

from argparse import ArgumentParser
from debian.deb822 import Packages
import lzma
import json

parser = ArgumentParser(prog="debian-packages")
parser.add_argument("--input", required=True)
parser.add_argument("--output", required=True)
args = parser.parse_args()

with lzma.open(args.input) as f:
    files = [
        {"filename": package["Filename"], "sha256": package["SHA256"]}
        for package in Packages.iter_paragraphs(f, use_apt_pkg=False)
    ]

with open(args.output, "w") as f:
    json.dump(files, f)
