#!/usr/bin/env python3

from argparse import ArgumentParser
from debian.deb822 import Packages
from collections import ChainMap
import lzma
import json

parser = ArgumentParser(prog="debian-packages")
parser.add_argument("inputs", nargs="*")
parser.add_argument("--output", required=True)
args = parser.parse_args()

data = ChainMap()

for file in args.inputs:
    with lzma.open(file) as f:
        data |= {
            package["Filename"]: package["SHA256"]
            for package in Packages.iter_paragraphs(f, use_apt_pkg=False)
        }

with open(args.output, "w") as f:
    json.dump(dict(data), f)
