#!/usr/bin/env python3
# sed -i 's|http://deb.debian.org/debian$|http://127.0.0.1:5000|' /etc/apt/sources.list.d/debian.sources

from flask import Flask, Response, abort, g
import sqlite3
import requests

app = Flask(__name__)

def get_db():
    db = getattr(g, '_database', None)
    if db is None:
        db = g._database = sqlite3.connect("/tmp/bookworm.db")
    return db

@app.teardown_appcontext
def close_connection(exception):
    db = getattr(g, '_database', None)
    if db is not None:
        db.close()

@app.route("/<path:subpath>")
def proxy(subpath):
    resp = requests.get(f'https://mirrors.tuna.tsinghua.edu.cn/debian/{subpath}')
    cur = get_db().cursor()
    cur.execute("SELECT sha256 FROM files WHERE filename = ?", (subpath,))
    row = cur.fetchone()
    if row == None:
        abort(404)
    return Response(resp.content, resp.status_code)

app.run()
