#!/usr/bin/env python3

from argparse import ArgumentParser
from debian.deb822 import Packages
import lzma

parser = ArgumentParser(prog="debian-packages")
parser.add_argument("--input", required=True)
parser.add_argument("--output", required=True)
args = parser.parse_args()

with lzma.open(args.input) as i:
    with open(args.output, "w") as o:
        o.write("{ uri, fetchurl }: [\n")
        for package in Packages.iter_paragraphs(i, use_apt_pkg=False):
            o.write(f"""  (let filename = "{package['Filename']}"; in {{\n""")
            o.write(f"""    name = filename;\n""")
            o.write(f"""    path = fetchurl {{ url = "${{uri}}/${{filename}}"; sha256 = "{package['SHA256']}"; }};\n""")
            o.write(f"""  }})\n""")
        o.write("]\n")
